window.reportFormAuditorStore = {
  url: {
    getUsers: '/local/components/twinpx/report.new/templates/.default/find.php',
    autosave:
      '/local/components/twinpx/report.new/templates/.default/autosave.php?IBLOCK_ID=23',
  },
  form: { action: '', method: 'POST' },
  hidden: [
    { name: 'FORM_ID', value: 245832 },
    { name: 'ID', value: 266547 },
    { name: 'sessid', value: '32699305da42c175f2c4a3d01091048c' },
  ],
  blocks: [
    {
      id: 1,
      title: 'Основные сведения',
      type: 'collapse',
      open: true,
      controls: [
        {
          type: 'text',
          property: 180,
          word: 'PROPERTY',
          label: 'Наименование организации&nbsp;*',
          required: true,
          value: '',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: 'Текущие данные из реестра',
            value: 'ООО "Тест-Аудит"',
            comment: '',
          },
        },
        {
          type: 'text',
          property: 181,
          word: 'PROPERTY',
          label: 'ОГРН&nbsp;*',
          required: true,
          value: '',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: 'Текущие данные из реестра',
            value: '999999998',
            comment: '',
          },
        },
        {
          type: 'ornz',
          property: 182,
          word: 'PROPERTY',
          label: 'ОРНЗ&nbsp;*',
          required: true,
          value: '',
          pattern: '^\\d{11}$',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: 'Текущие данные из реестра',
            value: '99999999998',
            comment: '',
          },
        },
      ],
    },
    {
      id: 2,
      title: 'Актуальные контакты',
      type: 'collapse',
      open: true,
      controls: [
        {
          type: 'text',
          property: 183,
          word: 'PROPERTY',
          label: 'E-mail&nbsp;*',
          required: true,
          value: '',
          pattern:
            "^[a-zA-Z0-9.!#$%&'*+\\/=?^_`{|}~-]+@[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?(?:\\.[a-zA-Z0-9](?:[a-zA-Z0-9-]{0,61}[a-zA-Z0-9])?)*$",
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: 'Текущие данные из реестра',
            value: 'vt@twinpx.ru',
            comment: '',
          },
        },
        {
          type: 'text',
          property: 184,
          word: 'PROPERTY',
          label: 'Телефон мобильный',
          required: false,
          value: '',
          pattern:
            '^([+]?[\\s0-9]+)?(\\d{3}|[(]?[0-9]+[)])?([-]?[\\s]?[0-9])+$',
          tab: false,
          bigLabel: false,
          completeBlock: { title: '', value: '', comment: '' },
        },
        {
          type: 'text',
          property: 185,
          word: 'PROPERTY',
          label: 'Телефон рабочий&nbsp;*',
          required: true,
          value: '',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: 'Текущие данные из реестра',
            value: '+79876543210',
            comment: '',
          },
        },
        {
          type: 'text',
          property: 186,
          word: 'PROPERTY',
          label: 'Сайт&nbsp;*',
          required: true,
          value: '',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: 'Текущие данные из реестра',
            value: 'www.twinpx.ru',
            comment: '',
          },
        },
      ],
    },
    {
      id: 3,
      title: 'Показатели деятельности',
      type: 'collapse',
      open: false,
      controls: [
        {
          type: 'text',
          property: 255,
          word: 'PROPERTY',
          label: 'Объем услуг (тыс. руб. без НДС)&nbsp;*',
          required: true,
          value: '123131313213131',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Выручка от оказания услуг (без НДС и аналогичных обязательных платежей), включая аудиторские услуги и прочие связанные с аудиторской деятельностью услуги. ',
          },
        },
        {
          type: 'text',
          property: 256,
          word: 'PROPERTY',
          label: 'Количество выданных аудиторских заключений&nbsp;*',
          required: true,
          value: '',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Общее количество выданных аудиторских заключений по результатам обязательного и инициативного аудита.',
          },
        },
        {
          type: 'text',
          property: 257,
          word: 'PROPERTY',
          label: 'Среднесписочная численность работников — всего&nbsp;*',
          required: true,
          value: '',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Определяется в порядке, установленном в приложении № 2 «Порядок заполнения формы расчета по страховым взносам» к приказу ФНС России от 18.09.2019 № ММВ-7-11/470@.',
          },
        },
        {
          type: 'text',
          property: 258,
          word: 'PROPERTY',
          label: 'из них аудиторов&nbsp;*',
          required: true,
          value: '',
          pattern: '',
          tab: 1,
          bigLabel: false,
          completeBlock: { title: '', value: '', comment: '' },
        },
        {
          type: 'text',
          property: 259,
          word: 'PROPERTY',
          label: 'Затраты на оплату труда (тыс. руб.)&nbsp;*',
          required: true,
          value: '12313213131321312313',
          pattern: '',
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Определяются в порядке, установленном п.8 ПБУ 10/99 «Расходы организации».',
          },
        },
      ],
    },
    {
      id: 4,
      title: 'Оказание аудиторских услуг',
      type: 'collapse',
      open: false,
      controls: [
        {
          type: 'select',
          property: 260,
          word: 'PROPERTY',
          label: 'Общественно значимым организациям&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'В значении части 1 статьи 5.1 Федерального закона от 30.12.2008 № 307-ФЗ «Об аудиторской деятельности».',
          },
        },
        {
          type: 'select',
          property: 261,
          word: 'PROPERTY',
          label: 'ОЗО на финансовом рынке&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Общественно значимым организациям на финансовом рынке. В значении части 3 статьи 5.1 Федерального закона от 30.12.2008 № 307-ФЗ «Об аудиторской деятельности».',
          },
        },
        {
          type: 'select',
          property: 262,
          word: 'PROPERTY',
          label: 'Организаций, с ценными бумагами допущены к торгам&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Организациям, ценные бумаги которых допущены к организованным торгам, а также организациям, бухгалтерская (финансовая) отчетность которых включается в проспект ценных бумаг.',
          },
        },
        {
          type: 'select',
          property: 263,
          word: 'PROPERTY',
          label: 'Кредитным организациям&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Кредитным организациям, головным кредитным организациям банковским группам, головным организациям банковских холдингов.',
          },
        },
        {
          type: 'select',
          property: 264,
          word: 'PROPERTY',
          label: 'Страховым организациям&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment: 'Страховым организациям, обществам взаимного страхования.',
          },
        },
        {
          type: 'select',
          property: 265,
          word: 'PROPERTY',
          label: 'Профессиональным участникам рынка ценных бумаг&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'Организациям, являющимся профессиональными участниками рынка ценных бумаг, бюро кредитных историй, клиринговыми организациями, организаторами торговли, негосударственными пенсионными фондами, управляющими компаниями инвестиционных фондов, паевыми инвестиционными фондами и негосударственными пенсионными фондами.',
          },
        },
      ],
    },
    {
      id: 5,
      title: 'Осуществление предпринимательской деятельности',
      type: 'collapse',
      open: false,
      controls: [
        {
          type: 'select',
          property: 190,
          word: 'PROPERTY',
          label: 'Оказание бухгалтерских услуг&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: { title: '', value: '', comment: '' },
        },
        {
          type: 'select',
          property: 191,
          word: 'PROPERTY',
          label: 'Оказание юридических услуг&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: { title: '', value: '', comment: '' },
        },
        {
          type: 'select',
          property: 266,
          word: 'PROPERTY',
          label:
            'В т.ч. операций с денежными средствами или иным имуществом&nbsp;*',
          options: [
            { label: 'Выберите', code: '' },
            { label: 'да', code: 'да' },
            { label: 'нет', code: 'нет' },
          ],
          selected: { label: 'Выберите', code: '' },
          required: true,
          tab: false,
          bigLabel: false,
          completeBlock: {
            title: '',
            value: '',
            comment:
              'В т.ч. подготовка или осуществление в рамках этих услуг от имени или по поручению своего клиента операций с денежными средствами или иным имуществом.',
          },
        },
      ],
    },
    {
      id: 6,
      controls: [
        {
          property: 1,
          word: 'FORM_AGREEMENT',
          label:
            'Я принимаю <a href="/privacy/" target="_blank">условия Пользовательского соглашения</a> и даю своё согласие СРО ААС на обработку моей персональной информации на условиях, определенных Политикой конфиденциальности.',
          required: true,
          type: 'checkbox',
          value: 'Y',
          checked: false,
          invalid: false,
        },
      ],
    },
  ],
  submit: { button: 'Отправить' },
};
